### DISCUSSION TITLE
Tab Spacing in YAML based DSL

### DISCUSSION THREAD

**Discussion by GSri30** [eclipse-xtext/xtext#2730] [Q&A] [answered]
I am trying to implement a DSL (YAML based) which looks something like this

```
guid: 9c358115-372e-4da6-aad2-ed9dc01bec20
table:
    name: rls_date_general
    db: rls_test
    schema: falcon_default_schema 
    db_table: rls_date_general
```

Now the following is the grammar I wrote

```
Model:
    objectEDocs+=ObjectEDoc*;

ObjectEDoc:
    GUIDElement | TableElement
;

GUIDElement:
	'guid' ':' guid=GUID
;

TableElement:
	'table' ':' table=TABLE
;

TABLE:
	table_rows+=IndentedTableRow+;

IndentedTableRow:
    '\t' table_row=TableRow;

TableRow:
	(table_key=TABLE_KEY ':' table_value=TABLE_VALUE)
;

terminal TABLE_KEY:
	'name' | 'db' | 'schema' | 'db_table';

terminal TABLE_VALUE:
	ID
;
```

When I am trying to introduce `IndentedTableRow` rule, the tests are failing for the above sample text. But I want to have a strict indentation rules setup in my grammar.

<img width="1121" alt="Screenshot 2023-07-04 at 3 19 48 PM" src="https://github.com/eclipse/xtext/assets/54752266/bc22615e-fdc5-4bd6-b559-0e2c21c55453">

Can anyone provide me any leads over this.

**Comment by cdietrich** [comment]
Did you check out https://www.eclipse.org/Xtext/documentation/307_special_languages.html#whitespace-aware-languages

**Reply by GSri30** [reply]
Yeah. But couldn't find any leads.

**Reply by cdietrich** [reply]
what do you mean by "lead"?

**Reply by GSri30** [reply]
I couldn't figure out why I'm getting the above error

**Reply by cdietrich** [reply, marked as answer]
did you try to use the documented begin and end tokens instead of hardcoding tab into keyword?

**Reply by GSri30** [reply]
Yeah, using `begin` and `end`, it's working properly.

Though, the problem now I'm facing is that when I use some nested key-value pairs using begin and end, its not able to identify the same key names.

Example
```
guid: 9c358115-372e-4da6-aad2-ed9dc01bec20
table:
    name: rls_date_general
    db: rls_test
    schema: falcon_default_schema 
    db_table: rls_date_general
    columns:
        name: some_name
```

I'm not able to distinguish between the `name` key inside `columns` and inside `table`.
